---
title: "Possible Data Frames"
editor: visual

format: 
  html:
    toc: true
    number-sections: true
    code-fold: false       # https://quarto.org/docs/output-formats/html-code.html
    code-summary: "Show the code"
    code-tools: true
    highlight-style: espresso # atom-one tango espresso

execute: 
  echo: true
  eval: true
  warning: false
  message: false
  fig-width: 9
---

```{r setup, include = FALSE}
library(tidyverse)
library(hrbrthemes)
library(skimr)

```

Below are some possible data frames for use in analysis projects.

## Sleep Health Data

Describes trends in sleep health/quality

```{r}
sleephlth <- read.csv("~/SUNY Geneseo/Classes/Fall 2023/DANL 200 (Team Pr)/dan-noone.github.io/Sleep_health_and_lifestyle_dataset.csv")
nvars <- format(round(ncol(sleephlth), 0), 
                nsmall=0, 
                big.mark=",") 
nobs <- format(round(nrow(sleephlth), 0), 
                nsmall=0, 
                big.mark=",")
```

Number of Variables: `r nvars` Number of Observations: `r nobs`

```{r, include=FALSE}
rmarkdown::paged_table(sleephlth)
```

### Description of Variables

```         
- **Person ID:** Unique identifier for each individual

- Gender: Gender of the person

- Age: The age of the person in years

- Occupation: Occupation of the person

- Sleep Duration: Length of time person sleeps per day (in hours)

- Quality of Sleep: Subjective rating from 1-10 of quality of sleep

- Physical Activity: Length of time person engages in physical activity per day (minutes per day)

- Stress Level: Subjective rating of stress level experienced by person from 1-10

- BMI Category: BMI category of the person
  -Underweight
  -Normal
  -Overweight
  
- Blood Pressure: Blood pressure measurement of the person, systolic over diastolic pressure

- Heart Rate: The resting heart rate of the person in beats per minute

- Daily Steps: The number of steps person takes per day

- Sleep Disorder: The presence or absence of a sleep disorder in the person
  -None
  -Insomnia
  -Sleep Apnea
```


